apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: textile-ai
resources:
  - namespace.yaml
  - postgres/pvc.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - ai/deployment.yaml
  - ai/service.yaml
  - api/configmap.yaml
  - api/uploads-pvc.yaml
  - api/deployment.yaml
  - api/service.yaml
  - api/ingress.yaml
  - api/hpa.yaml
  - api/pdb.yaml
  - web/configmap.yaml
  - web/deployment.yaml
  - web/service.yaml
  - web/ingress.yaml
  - web/hpa.yaml
  - web/pdb.yaml
